version: '3'
services:
  movie:
    image: narendradh/movie:v1
    ports:
      - "8000:80"
    deploy:
      replicas: 3

  recharge:
    image: narendradh/recharge:v1
    ports:
      - "8001:80"
    deploy:
      replicas: 3

  payments:
    image: narendradh/payments:v1
    ports:
      - "8002:80"
    deploy:
      replicas: 3
